#!/bin/bash
set -e

echo "Начинаем очистку системы..."

# Остановить и отключить сервис
systemctl stop fireplace.service || true
systemctl disable fireplace.service || true

# Обновить systemd
systemctl daemon-reload

# Удалить скрипт
echo "Удаляем конфигурационный файл..."
rm -f /mnt/data/python/fireplace2mqtt.py

# Удалить конфигурационный файл
echo "Удаляем конфигурационный файл..."
rm -f /mnt/data/python/fireplace_config.json

# Удалить json схему
echo "json схему..."
rm -f /usr/share/wb-mqtt-confed/schemas/wb-mqtt-fireplace.schema.json

# Удалить пустую директорию
echo "Удаляем директорию, если она пуста..."
rmdir --ignore-fail-on-non-empty /mnt/data/python/

echo "Очистка завершена успешно."
