name: Build DEB Package

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create directories
        run: |
          mkdir -p fireplace2mqtt-package/DEBIAN
          mkdir -p fireplace2mqtt-package/mnt/data/python
          mkdir -p fireplace2mqtt-package/etc/systemd/system
      - name: Copy files
        run: |
          cp fireplace_config.json fireplace2mqtt-package/mnt/data/python/
          cp fireplace2mqtt.py fireplace2mqtt-package/mnt/data/python/
          cp fireplace.service fireplace2mqtt-package/etc/systemd/system/
          cp DEBIAN/control fireplace2mqtt-package/DEBIAN/
          cp DEBIAN/postinst fireplace2mqtt-package/DEBIAN/
          cp DEBIAN/prerm fireplace2mqtt-package/DEBIAN/
      - name: Build DEB
        run: |
          version=$(echo $GITHUB_REF | cut -d '/' -f3)  # Извлекает версию из тега (например, v1.0.3 → 1.0.3)
          dpkg-deb --build fireplace2mqtt-package fireplace2mqtt_${version}_all.deb
      
      - name: Publish to Release
        uses: softprops/action-gh-release@v1
        with:
          files: fireplace2mqtt_${{ env.VERSION }}_all.deb
